spring.application.name=testtodo

server.port=8098

## Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/testtodo
spring.datasource.username=postgres
spring.datasource.password=Rena2120
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true